package com.netnumeri.server.finance.beans

enum IndicatorEnum {

    SimpleMovingAverage,
    WeightedMovingAverage,
    SingularSpectrumTrend,
    SingularSpectrumPrediction,
    PriceChannelUpper,
    PriceChannelLower,
    UpperBollingerBand,
    LowerBollingerBand,
    kVHF,
    SimpleMovingVariance,
    kSMD,
    kSMC,
    Momentum,
    To,
    Macd,
    RateOfChange,
    RSI,
    RSI2,
    kCCI,
    kKRI,
    kOSC,
    kPCR,
    kFI,
    kD,
    kK,
    kVA,
    kVAI,
    kCHO,
    TrueChange,      // TR   True Range
    AverageTrueChange,     // ATR  Average True Range
    kUserDefined,
    MoneyFlowOverPeriod,
    AccumulateDistributionOverPeriod,
    ChaikinOscillatorOverPeriod,
    ChaikinMoneyFlowOverPeriod,
    AroonOscillatorOverPeriod,
    AroonDownOverPeriod,
    AroonUpOverPeriod,
    TrueRangePeriod,
    kFastStochasticPeriod,
    dStochastic,
    DStochasticSmoothed,
    ChaikinVolatility,
    kMACDSignal,
    PlusDirectionalMovementPeriod,
    MinusDirectionalMovementPeriod,
    PriceActionOverPeriod,
    BalanceOfPowerOverPeriod,
    MarketFacilitationIndexOverPeriod,
    CommodityChannelIndexOverPeriod,
    MomentumPctPeriod,
    GeometricMovingAverage,
    LinearlyWeightedMovingAverage,
    TriangularMovingAverage,
    ExponentiallyWeightedMovingAverage,
    Kairi,
    RateOfChangePeriod;

}
